name: print payload

on:
  workflow_call:

jobs:
  print-payload:
    runs-on: ubuntu-latest
    steps:
      - run: printf "%s" "$PAYLOAD"
        env:
          PAYLOAD: ${{ toJSON(github.event) }}
