name: print payload

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: 0 23 * * *

jobs:
  print-payload:
    runs-on: ubuntu-latest
    steps:
      - run: printf "%s" "$PAYLOAD"
        env:
          PAYLOAD: ${{ toJSON(github.event) }}
